# Generated by Django 3.1.7 on 2021-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-image.jpg', upload_to='profile_pics'),
        ),
    ]
